version: '3.4'

volumes:
  dbvol:
    name: JumpDirDB-SgdWtyp4IAw8

services:
  web:
    # image: jumpdir:debug
    # image: jumpdir:prod
    depends_on:
      - db
  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    # volumes:
    #   - dbvol:/var/lib/postgresql/data
